name: whatsapp_ui
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  country_picker: ^2.0.27

  # Firebase packages - UPDATED VERSIONS
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.2
  firebase_storage: ^12.3.6

  # State management
  flutter_riverpod: ^2.4.9

  # Utilities & UI
  image_picker: ^1.2.0
  flutter_contacts: ^1.1.9+2
  uuid: ^4.5.1
  date_format: ^2.0.9
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  video_player: ^2.10.0
  emoji_picker_flutter: ^4.3.0
  enough_giphy_flutter: ^0.4.2
  flutter_sound: ^9.28.0
  permission_handler: ^11.0.0
  path_provider: ^2.1.5
  audioplayers: ^6.5.1
  cloudinary_public: ^0.23.1
  swipe_to: ^1.0.6
  story_view: ^0.16.6

  # Agora (Video call)
  agora_rtc_engine: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/backgroundImage.png
    - assets/bg09.png
    - assets/11_a.jpg